const patients = [
    {
      id: 1,
      name: "Brad Pitt",
      age: 64,
      gender: "male",
      prescriptionsAmount: 6,
    },
    {
      id: 2,
      name: "Angelina Jolie",
      age: 57,
      gender: "female",
      prescriptionsAmount: 16,
    },
    {
      id: 3,
      name: "Leonardo DiCaprio",
      age: 55,
      gender: "male",
      prescriptionsAmount: 88,
    },
    {
      id: 4,
      name: "Meryl Streep",
      age: 75,
      gender: "female",
      prescriptionsAmount: 88,
    },
    {
      id: 5,
      name: "Denzel Washington",
      age: 64,
      gender: "male",
      address: "Washington",
      treatmentStatus: false,
      prescriptionsAmount: 40,
    },
    {
      id: 6,
      name: "Kate Winslet",
      age: 52,
      gender: "female",
      address: "London",
      treatmentStatus: false,
      prescriptionsAmount: 15,
    },
    {
      id: 7,
      name: "Tom Hanks",
      age: 73,
      gender: "male",
      address: "New-York",
      treatmentStatus: false,
      prescriptionsAmount: 40,
    },
    {
      id: 8,
      name: "Natalie Portman",
      age: 41,
      gender: "female",
      address: "Jerusalem",
      treatmentStatus: false,
      prescriptionsAmount: 9,
    },
]
export default patients